### ISSUE TITLE
PrismaClientInitializationError

### ISSUE THREAD

**Issue by YounggilLee** [YounggilLee/store#1]
⨯ PrismaClientInitializationError: 
Invalid `prisma.product.findMany()` invocation:
Can't reach database server at `db.aws-0-ca-central-1.pooler.supabase.co:6543`
Please make sure your database server is running at `db.aws-0-ca-central-1.pooler.supabase.co:6543`.
    at async fetchFeaturedProducts (./utils/actions.ts:9:22)
    at async FeaturedProducts (./components/home/FeaturedProducts.tsx:17:22)

**Comment by YounggilLee** [comment]
The password had numbers special charter in it.
So make sure to just put alphabets in the db password no numbers no special chars in Supabase
